version: '3'

services:
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb:/var/lib/influxdb
    restart: unless-stopped
    networks:
      - app_network  # Use the shared network
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana:/var/lib/grafana
    restart: unless-stopped
    networks:
      - app_network  # Use the shared network

volumes:
  influxdb:
  grafana:

networks:
  app_network:
    external: true      