version: '3.8'

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    command: ollama run deepseek-r1:1.5b
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama

volumes:
  ollama:
