version: '3.8'

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    entrypoint: ["/bin/sh", "-c"]
    command: |
      "ollama serve & sleep 2 && ollama run deepseek-r1:1.5b"

volumes:
  ollama:
