################################################################################
# Node-RED Stack or Compose
################################################################################
# docker stack deploy node-red --compose-file docker-compose-node-red.yml
# docker-compose -f docker-compose-node-red.yml -p myNoderedProject up
################################################################################
#sudo docker-compose up -d
#sudo docker-compose down
version: "3.7"

services:
  node-red:
    restart: unless-stopped
    image: nodered/node-red:latest-debian
    environment:
      - TZ=Europe/Bucharest
    ports:
      - "1880:1880"
    volumes:
      - /home/recoder/RECODER-COMPOSE/node-red_docker/data:/data
    networks:
      - app_network  # Use the shared network
    # depends_on:
    #   - homeassistant
volumes:
  node-red-data:

networks:
  app_network:
    external: true