services:  
  nginx:  
    image: nginx:alpine  
    container_name: nginx_reverse_proxy  
    volumes:  
      - ./nginx.conf:/etc/nginx/nginx.conf  
      - /etc/letsencrypt:/etc/letsencrypt:ro  # read-only certs
    ports:  
      - 82:82  
      - 80:80
      - 443:443  
    restart: unless-stopped  
    networks:  
      - app_network  

networks:  
  app_network:  
    external: true  
