services:  
  nginx:  
    image: nginx:alpine  
    container_name: nginx_reverse_proxy  
    volumes:  
      - ./nginx.conf:/etc/nginx/nginx.conf  
    ports:  
      - 82:82 
      - 443:443  
    restart: unless-stopped  
    networks:  
      - app_network  # Use the shared network  

networks:  
  app_network:  
    external: true  