version: "3.9"

services:
  yolov8:
    image: ultralytics/yolov8:latest
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    environment:
      - MODEL_PATH=/app/data/yolov8.pt

  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/share/nginx/html