---
services:
  ispyagentdvr:
    image: mekayelanik/ispyagentdvr:5.8.0.0
    container_name: ispyagentdvr
    environment:
      - PUID=1000
      - PGID=1000
      - AGENTDVR_WEBUI_PORT=8090 
      - TZ=Europe/Bucharest
    volumes:
      - /home/recoder/RECODER-COMPOSE/Docker-agentDVR/folders/config:/AgentDVR/Media/XML
      - /mnt/data/recordings:/AgentDVR/Media/WebServerRoot/Media
      - /home/recoder/RECODER-COMPOSE/Docker-agentDVR/folders/commands:/AgentDVR/Commands
    ports:
      - 8090:8090
      - 3478:3478/udp
      - 50000-50100:50000-50100/udp
    restart: unless-stopped
    # network_mode: "bridge"  # Optional: use "host"
    networks:
      - app_network  # Use the shared network
        #

networks:
  app_network:
    external: true    