---
services:
  ispyagentdvr:
    image: mekayelanik/ispyagentdvr:latest
    container_name: ispyagentdvr
    environment:
      - PUID=1000
      - PGID=1000
      - AGENTDVR_WEBUI_PORT=8090 
      - TZ=Asia/Dhaka
    volumes:
      - /home/recoder/RECODER-COMPOSE/Docker-agentDVR/folders/config:/AgentDVR/Media/XML
      - /home/recoder/RECODER-COMPOSE/Docker-agentDVR/folders/recordings:/AgentDVR/Media/WebServerRoot/Media
      - /home/recoder/RECODER-COMPOSE/Docker-agentDVR/folders/commands:/AgentDVR/Commands
    ports:
      - 8090:8090
      - 3478:3478/udp
      - 50000-50100:50000-50100/udp
    restart: unless-stopped